define([
    'jquery'
], function ($) {
    'use strict';

    // DO NOT EDIT THIS FILE - IT SHOULD REMAIN EMPTY
    // DOCS: http://docs.cssoftsolutions.com/m2/extensions/cscheckout/customization/custom-js/
});
